services:
  app:
    user: "${USER_ID:-1000}"
    hostname: "${HOST_NAME:-mdop}"
    image: mlproject-template
    platform: linux/amd64
    container_name: mlproject-template-container
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        USER_NAME: "${USER_NAME:-nhatminh}"
        USER_ID: "${USER_ID:-1000}"
    volumes:
      - ./:/app/
      - ~/.config/gcloud/:/home/${USER_NAME:-nhatminh}/.config/gcloud
    ports:
      - 8080:8080

    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
    ipc: host
    init: true